CREATE TABLE `led_effect` (
`EFFECT_NUM` BIGINT(20) NOT NULL AUTO_INCREMENT,
`PROJECT_NAME` VARCHAR(50) NOT NULL DEFAULT '0',
`MCU_NAME` VARCHAR(50) NOT NULL DEFAULT '0',
`PIN_SETUP` BIGINT(20) NOT NULL DEFAULT '0',
`NUM_LEDS` SMALLINT(6) NOT NULL DEFAULT '0',
`LIGHTING_EFFECT` INT(11) NOT NULL DEFAULT '0',
`EFFECT_START` SMALLINT(6) NOT NULL DEFAULT '0',
`EFFECT_DURATION` SMALLINT(6) NOT NULL DEFAULT '0',
`LED_POSITION_ARRAY` VARCHAR(999) NOT NULL DEFAULT '0',
`LED_COLOR_ARRAY` VARCHAR(999) NOT NULL DEFAULT '0',
PRIMARY KEY (`EFFECT_NUM`),
INDEX `FK_led_effect_mcu` (`MCU_NAME`),
INDEX `FK_led_effect_mcu_pins` (`PIN_SETUP`),
INDEX `FK_led_effect_lighting_effects` (`LIGHTING_EFFECT`),
INDEX `FK_led_effect_led_project` (`PROJECT_NAME`),
CONSTRAINT `FK_led_effect_led_project` FOREIGN KEY (`PROJECT_NAME`) REFERENCES `led_project` (`PROJECT_NAME`) ON UPDATE CASCADE,
CONSTRAINT `FK_led_effect_lighting_effects` FOREIGN KEY (`LIGHTING_EFFECT`) REFERENCES `lighting_effects` (`LIGHTING_EFFECT`) ON UPDATE CASCADE,
CONSTRAINT `FK_led_effect_mcu` FOREIGN KEY (`MCU_NAME`) REFERENCES `mcu` (`MCU_NAME`) ON UPDATE CASCADE,
CONSTRAINT `FK_led_effect_mcu_pins` FOREIGN KEY (`PIN_SETUP`) REFERENCES `mcu_pins` (`PIN_SETUP`) ON UPDATE CASCADE
)
COMMENT='This table will hold all led effects for all microcontrollers in all projects'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;

