CREATE TABLE `mcu_pins` (
	`PIN_SETUP` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` VARCHAR(50) NULL DEFAULT NULL,
	`MCU_NAME` VARCHAR(50) NOT NULL,
	`DATA_PIN` TINYINT(4) NOT NULL,
	`CLOCK_PIN` TINYINT(4) NOT NULL,
	PRIMARY KEY (`PIN_SETUP`),
	INDEX `FK_mcu_pins_mcu` (`MCU_NAME`),
	CONSTRAINT `FK_mcu_pins_mcu` FOREIGN KEY (`MCU_NAME`) REFERENCES `mcu` (`MCU_NAME`) ON UPDATE CASCADE
)
COMMENT='This table will hold the different pin setups for a project\'s selected MCU'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
